# Welcome to Jekyll!

# Site settings
title: Your awesome title
email: your-email@example.com
description: >- 
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "" # If your site is hosted on a subpath, e.g., /blog
url: "https://abbesachraf.github.io/abbesachraf.github.io" # Add the full base URL for your site
twitter_username: jekyllrb
github_username:  abbesachraf

# Build settings
# theme: minimal-mistakes-jekyll
remote_theme: "mmistakes/minimal-mistakes"

# Plugins
plugins:
  - jekyll-feed
  - jekyll-include-cache
  - jekyll-remote-theme

# Exclude from processing.
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
