title: "Colonneil Blog"
name: "Colonneil"
email: abbesashraf@gmail.com
url: "https://colonneil.me"
baseurl: ""
repository: "abbesachraf/abbesachraf.github.io"

twitter_username: colonneila
github_username: abbesachraf

# Build settings
remote_theme: "mmistakes/minimal-mistakes"
minimal_mistakes_skin: dark

# Plugins
plugins:
  - jekyll-feed
  - jekyll-include-cache
  - jekyll-remote-theme
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-archives
  - jekyll-seo-tag

whitelist:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jekyll-include-cache
  - jekyll-archives
  - jekyll-seo-tag

include:
  - _pages
  - assets
  - index.html

exclude:
  - TODO.md
  - README.md
  - "*.org"
  - "*ltximg*"
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/

markdown: kramdown

author:
  name: "Achraf Abbes"
  avatar: "/assets/images/headshot.gif"
  bio: "I’m passionate about web development, cybersecurity, and solving complex technical challenges. I enjoy exploring cutting-edge technologies, participating in Capture The Flag (CTF) competitions, and discovering new vulnerabilities through bug bounty hunting."
  location: "Tunisia, TN"
  github: abbesachraf
  linkedin: abbesachraf
  email: abbesashraf@gmail.com

comments:
  provider: "disqus"
  disqus:
    shortname: "pwills-com"

analytics:
  provider: "google"
  google:
    tracking_id: "UA-116208936-1"

paginate: 3 # number of posts to show
paginate_path: /page:num/

# default YAML front matter
defaults:
  - scope:
      path: ""
    values:
      layout: single
      mathjax: true
      author_profile: true
      class: wide
      title: " "
      title_separator: "|"
  - scope:
      type: posts
    values:
      toc: true
      toc_label: "Contents"
      read_time: false
      comments: true
  - scope:
      path: ""
      type: portfolio
    values:
      author_profile: false
      excerpt: ""
      sidebar:
        nav: "portfolio"

# collections
collections:
  portfolio:
    output: true
